name: Build demo
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 */1 * * *

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        
      - run: npm install
      
      - run: ./node_modules/.bin/esbuild index.ts --bundle --outfile=public/build/bundle.js
      
      - run: ./clone.sh
      
      - run: cp index.html public
      
      - uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'public'
          push: git push origin demo --set-upstream --force
